using CaptureTool.Application.Abstractions.UseCases;

namespace CaptureTool.Application.Abstractions.Settings.UpdateEditWarnBeforeDiscard;

public interface IUpdateEditWarnBeforeDiscardUseCase : IUseCase<UpdateEditWarnBeforeDiscardRequest, UpdateEditWarnBeforeDiscardResponse>, IConditional<UpdateEditWarnBeforeDiscardRequest>
{
}
