using CaptureTool.Application.Abstractions.Localization;
using CaptureTool.Domain.Analysis;
using CaptureTool.Domain.Analysis.Payloads;
using System.Globalization;

namespace CaptureTool.Presentation.Features.CaptureDetails;

/// <summary>A focused read projection. Raw facts, classification and provider diagnostics stay out of the pane.</summary>
public sealed class CaptureDetailsContent
{
    public string AltText { get; private init; } = string.Empty;
    public string Summary { get; private init; } = string.Empty;
    public string SuggestedName { get; private init; } = string.Empty;
    public string Description { get; private init; } = string.Empty;
    public bool HasSummaryInputs => Description.Length > 0 || Passages.Any(passage => !string.IsNullOrWhiteSpace(passage.Text));
    public IReadOnlyList<CaptureTextPassage> Passages { get; private init; } = [];
    public bool HasLimitedCoverage { get; private init; }
    public bool HasContent => AltText.Length > 0 || Summary.Length > 0 || Description.Length > 0 || Passages.Count > 0;

    public static CaptureDetailsContent Create(CaptureAnalysisRecord record, ILocalizationService localization) => new()
    {
        AltText = record.Results.Select(result => result.Payload).OfType<ImageAltTextMetadata>().SingleOrDefault()?.Suggestion?.Text ?? string.Empty,
        Summary = string.Join(" ", record.Results.Select(result => result.Payload).OfType<CaptureSynopsisMetadata>()
            .SelectMany(synopsis => synopsis.Summary).Select(statement => statement.Text)),
        // Retain names generated by the older combined action without running a model again.
        SuggestedName = record.Results.Select(result => result.Payload).OfType<CaptureNameMetadata>().SingleOrDefault() is { } name
            ? name.Suggestion?.Text ?? string.Empty
            : record.Results.Select(result => result.Payload).OfType<CaptureSynopsisMetadata>().SingleOrDefault()?.Title?.Text ?? string.Empty,
        Description = string.Join(Environment.NewLine, record.Results.Select(result => result.Payload).OfType<DescriptionMetadata>()
            .SelectMany(payload => payload.Descriptions).Select(description => description.Timestamp is { } time
                ? $"{Time(time)}  {description.Text}" : description.Text)),
        Passages = CaptureTextPassage.From(record, localization),
        HasLimitedCoverage = record.Results.Any(result => result.Payload is CaptureSynopsisMetadata { Coverage.IsComplete: false } or ImageAltTextMetadata { Coverage.IsComplete: false }) ||
            record.MediaKind == AnalysisMediaKind.Video && record.Results.Any(result => result.Payload is TextRecognitionMetadata)
    };

    internal static string Time(TimeSpan time) => time.TotalHours >= 1
        ? $"{(long)time.TotalHours}:{time.Minutes:00}:{time.Seconds:00}" : $"{time.Minutes}:{time.Seconds:00}";
    internal static string FormatSize(long bytes)
    {
        string[] units = ["B", "KiB", "MiB", "GiB", "TiB", "PiB", "EiB"];
        double value = bytes;
        int unit = 0;
        while (value >= 1024 && unit < units.Length - 1) { value /= 1024; unit++; }
        return value.ToString(unit == 0 ? "N0" : "0.##", CultureInfo.CurrentCulture) + " " + units[unit];
    }
}
