<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CaptureTool.Application.Abstractions\CaptureTool.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\CaptureTool.Infrastructure\CaptureTool.Infrastructure.csproj" />
  </ItemGroup>

</Project>
