using CaptureTool.Application.Abstractions.UseCases;

namespace CaptureTool.Application.Abstractions.Features.CaptureOverlay.GoBackFromCaptureOverlay;

public interface IGoBackFromCaptureOverlayUseCase : IUseCase<GoBackFromCaptureOverlayRequest, GoBackFromCaptureOverlayResponse>, IConditional<GoBackFromCaptureOverlayRequest>
{
}