<Project Sdk="MSTest.Sdk/4.0.2">

  <!-- Project properties -->
  <PropertyGroup>
    <UseVSTest>true</UseVSTest>
  </PropertyGroup>

  <!-- Project references -->
  <ItemGroup>
    <ProjectReference Include="..\..\src\CaptureTool.Application\CaptureTool.Application.csproj" />
    <ProjectReference Include="..\..\src\CaptureTool.Domain\CaptureTool.Domain.csproj" />
    <ProjectReference Include="..\..\src\CaptureTool.Domain.Analysis\CaptureTool.Domain.Analysis.csproj" />
    <ProjectReference Include="..\..\src\CaptureTool.Infrastructure\CaptureTool.Infrastructure.csproj" />
  </ItemGroup>

  <!-- Package references -->
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeCoverage" />
    <PackageReference Update="MSTest.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
