using CaptureTool.Application.Abstractions.UseCases;

namespace CaptureTool.Application.Abstractions.Settings.UpdateVideoCaptureAutoSave;

public interface IUpdateVideoCaptureAutoSaveUseCase : IUseCase<UpdateVideoCaptureAutoSaveRequest, UpdateVideoCaptureAutoSaveResponse>, IConditional<UpdateVideoCaptureAutoSaveRequest>
{
}